# -*- mode: ruby -*-
# vi: set ft=ruby :

# 检查Vagrant版本
Vagrant.require_version ">= 1.6.0"

# 定义虚拟机配置
boxes = [
    {
        :name => "ansible-node1",
        :mem => "1024",
        :cpu => 1
    },
    {
        :name => "ansible-node2",
        :mem => "1024",
        :cpu => 1
    },
    {
        :name => "ansible-node3",
        :mem => "1024",
        :cpu => 1
    },
]

# 配置Vagrant
Vagrant.configure(2) do |config|

  # 设置虚拟机镜像
  config.vm.box = "generic/ubuntu2004"
  # 遍历虚拟机配置
  boxes.each do |opts|
    # 定义虚拟机
    config.vm.define opts[:name] do |config|
      # 设置虚拟机主机名
      config.vm.hostname = opts[:name]
      # 配置VMware Fusion提供者
      config.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = opts[:mem]
        v.vmx["numvcpus"] = opts[:cpu]
      end
      # 配置VirtualBox提供者
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end
      # 配置Hyper-V提供者
      config.vm.provider "hyperv" do |v|
        v.cpus = opts[:cpu]
        v.maxmemory = opts[:mem]
        v.memory = opts[:mem]
      end
    end
  end
  # 配置虚拟机初始化脚本
  config.vm.provision "shell", privileged: false, path: "./setup.sh"
end
